# Generated by Django 5.2.4 on 2025-09-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacote',
            old_name='vendedor',
            new_name='vendedor_id',
        ),
    ]
