# Generated by Django 5.2.4 on 2025-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_vendedor_pacote_vendedor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cobranca_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
